name: CI

permissions:
  contents: read

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  format:
    runs-on: ${{matrix.os}}-${{matrix.os-version}}
    strategy:
      matrix: &matrix-config
        go-version: ["1.12", "1.16"]
        os: [ubuntu, windows]
        include:
          - os-version: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Environment
        uses: actions/setup-go@v7.0.0
        with:
          go-version: ${{matrix.go-version}}

      - name: Format Validation
        shell: bash
        id: format-validation
        run: test -z "$(gofmt -l .)"
        
  dependencies:
    runs-on: ${{matrix.os}}-${{matrix.os-version}}
    needs: [ format ]
    strategy:
      matrix: *matrix-config

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Environment
        uses: actions/setup-go@v7.0.0
        with:
          go-version: ${{matrix.go-version}}

      - name: Check Dependencies
        id: check-dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
          
  analysis:
    runs-on: ${{matrix.os}}-${{matrix.os-version}}
    needs: [ dependencies ]
    strategy:
      matrix: *matrix-config

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Environment
        uses: actions/setup-go@v7.0.0
        with:
          go-version: ${{matrix.go-version}}

      - name: Check Code Errors
        id: check-code-errors
        run: go vet ./...
  test:
    runs-on: ${{matrix.os}}-${{matrix.os-version}}
    needs: [ analysis ]
    strategy:
      matrix: *matrix-config
      
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Environment
        uses: actions/setup-go@v7.0.0
        with:
          go-version: ${{matrix.go-version}}

      - name: Create Coverage Folder
        shell: bash
        run: mkdir -p coverage

      - name: Test Execution
        run: go test ./... -race -count=1 -coverprofile=coverage/coverage-${{matrix.os}}.out

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: coverage-${{matrix.os}}-${{matrix.go-version}}
          path: coverage/
          if-no-files-found: error

  build:
    runs-on: ${{matrix.os}}-${{matrix.os-version}}
    needs: [ test ]
    strategy:
      matrix: *matrix-config

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup Environment
        uses: actions/setup-go@v7.0.0
        with:
          go-version: ${{matrix.go-version}}

      - name: Generate Build
        id: build
        run: go build ./...

      - name: Summary
        run: echo "${{matrix.os}}-${{matrix.os-version}} + Go ${{matrix.go-version}} -> ${{steps.build.outcome}}" >> $GITHUB_STEP_SUMMARY


          
